---

# Install (present) or remove (absent)?
ess_state: present

# Required but not provided ------------------------------------------------------------

# The Namespace to install to (expected to exist)
ess_namespace: SetMe
# The Namespace Service Account to use (expected to exist)
ess_service_account: SetMe
# The hostname for our event streams (WebSockets)
# For example 'example.com'.
# Sockets will be made available at wss://{{ ess_hostname }}/event-stream/<id>
ess_ws_hostname: SetMe
# The AMQP URL for the RabbitMQ server.
# This must include a username and password and typically an exchange.
# For example 'amqp://username:password@rabbitmq:5672/es'
ess_ampq_url: SetMe
# What image tag do you want to deploy?
ess_image_tag: SetMe
# SSL certificate issuer?
# One of 'production', 'staging' or blank (for no SSL).
ess_cert_issuer:

# Required with defaults ---------------------------------------------------------------

# Deploy the ingress definition?
# One of 'present' or 'absent'.
ess_ingress_state: present

# Our image details
ess_image_owner: informaticsmatters

# Always pull the image, regardless of tag?
# Set to anything to apply.
ess_pull_policy_always:

# Storage class for the DB and logging (' ' implies default)
ess_shared_volume_volume_storageclass: ' '
ess_log_volume_volume_storageclass: ' '

# Pod resource requests and limits
ess_api_cpu_request: 10m
ess_api_cpu_limit: 1
ess_api_mem_request: 128Mi
ess_api_mem_limit: 128Mi
