---

- name: Remove Event Stream
  kubernetes.core.k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    state: absent
  loop:
  - ingress
  - service-ws
  - service-api
  - deployment
  - pvc-database
  - pvc-log
