---

- name: Prep
  include_tasks: prep.yaml
  vars:
    kubeconfig: "{{ ess_kubeconfig }}"

# The 'installation' must also be set.

- name: Assert installation name is defined
  ansible.builtin.assert:
    that:
    - ess_installation_name | string | length > 0
    - ess_installation_name != 'SetMe'
    msg: "You must define 'ess_installation_name'"

# Include sensitive (Ansible Vault) variables based on the installation name.
# We include 'sensitive-local.vault' variables if the installation name is 'local'.
# The user will need to provide the vault password.

- name: Include sensitive (vault) variables ({{ ess_installation_name }})
  ansible.builtin.include_vars:
    file: sensitive-{{ ess_installation_name }}.vault
  when: ess_installation_name | length > 0

# Go...

- name: Go
  module_defaults:
    group/k8s:
      host: "{{ k8s_auth_host }}"
      api_key: "{{ k8s_auth_api_key }}"
      kubeconfig: "{{ k8s_auth_kubeconfig }}"
  block:

  - name: Deploy
    ansible.builtin.include_tasks: deploy.yaml
    when: ess_state == 'present'

  - name: Undeploy
    ansible.builtin.include_tasks: undeploy.yaml
    when: ess_state == 'absent'
